import 'package:get/get_navigation/src/root/internacionalization.dart';

class Strings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'login': 'Login',
          'required_field': 'Required Field',
          'phone': 'Phone',
          'phone_number': 'Phone Number',
          'email': 'Email',
          'try_again': "Try Again",
          'no_internet': "Please Check Your Internet Connection!",
          'verify_otp': "Verify OTP",
          'verify_otp_hint1':
              "Enter the four-digit code that you were sent over mobile SMS.",
          'click_on_': "Click On ",
          'resend_': "Resend,",
          'otm_received_note': " if you do not receive after 2 minutes",
          'submit': "Submit",
          'enter_otp': "Enter OTP",
          'otp_resend_success_message': "Otp resend",
          'home': "Home",
          'profile': "Profile",
          'more': "More",
          'product_list': "Product List",
          'products': "Products",
          'stores': "Stores",
          'suppliers': "Suppliers",
          'vendors': "Vendors",
          'empty_data_message': "No data found",
          'sku': "SKU",
          'price': "Price",
          'manufacturer': "Manufacturer",
          'category': "Category",
          'select_phone_extension': "Select phone extension",
          'search': "Search",
          'settings': "Settings",
          'logout': "Logout",
          'logout_msg': "Are you sure you want to logout?",
          'yes': "Yes",
          'no': "No",
          'add_product': "Add Product",
          'edit_product': "Edit Product",
          'product_short_name': "Product Short Name",
          'product_name': "Product Name",
          'supplier': "Supplier",
          'length': "Length",
          'width': "Width",
          'height': "Height",
          'dimensions_': "Dimensions (Length * Width * Height)",
          'length_unit': "Length Unit",
          'weight': "Weight",
          'weight_unit': "Weight Unit",
          'model': "Model",
          'tax_percentage': "Tax (%)",
          'description': "Description",
          'status': "Status",
          'upload_pictures': "Upload Pictures",
          'address': "Address",
          'company_name': "Company Name",
          'save': "Save",
          'qr_code': "Qr Code",

        },
        'hi_IN': {'login': 'Login'}
      };
}
